### ISSUE TITLE
Engergy typos for recipe functions

### ISSUE THREAD

**Issue by randomflyingtaco** [LovelySanta/FactorioModLib#2]
The following recipe functions have "Engergy" instead of "Energy":

LSlib.recipe.setEngergyRequired
LSlib.recipe.editEngergyRequired
LSlib.recipe.getEngergyRequired

but fixing it would mean that all mods using those would also have to update.  Maybe make properly spelled functions and have the old ones call into the new ones?

**Comment by LovelySanta** [comment]
Thanks for the report. This is fixed for the next release. I've added in backwards compatibility for now.
