### ISSUE TITLE
Crash when duplicating non-existent recipe

### ISSUE THREAD

**Issue by randomflyingtaco** [LovelySanta/FactorioModLib#3]
The first half of recipe.duplicate looks like it is designed to handle cases where the recipe you are trying to duplicate does not exist, but since the second half isn't in an else block, it still causes a crash "attempt to index local 'copy' (a nil value)"

https://github.com/LovelySanta/FactorioModLib/blob/9e3dbea11272404a2f786387a944b5e99e01934a/LSlib/prototyping/recipe/recipe-creation.lua#L15

**Comment by LovelySanta** [comment]
That's indeed an issue. Seems like it's just missing a return statement :D I'll fix it for the next release.

```lua
  function LSlib.recipe.duplicate(recipeName, newRecipeName)
    if not data.raw["recipe"][recipeName] then
      return LSlib.recipe.create(newRecipeName)
    end
    LSlib.recipe.recipePrototypeCleanup(recipeName)

    local copy = util.table.deepcopy(data.raw["recipe"][recipeName])
    copy.name = newRecipeName
    data:extend{copy}
  end
```

**Comment by randomflyingtaco** [comment]
Sounds good, should it also log a message that you tried to duplicate a recipe that doesn't exist?

**Comment by LovelySanta** [comment]
Not everything has logging tho... I should unify that a bit more, that's another issue

**Comment by LovelySanta** [comment]
Fixed in https://github.com/LovelySanta/FactorioModLib/commit/ab40a1582bc360123b8f07f8a59eb710abee0c34.
