### ISSUE TITLE
LSlib.recipe.getResultCount behavior doesn't really make sense

### ISSUE THREAD

**Issue by randomflyingtaco** [LovelySanta/FactorioModLib#5]
https://github.com/LovelySanta/FactorioModLib/blob/ab40a1582bc360123b8f07f8a59eb710abee0c34/LSlib/prototyping/recipe/recipe-result.lua#L189

LSlib.recipe.getIngredientCount returns the number of different ingredients which is fine.
LSlib.recipe.getResultCount returns the amount of the first listed result and has a resultName parameter which is completely unused.  I'm not sure what the intended functionality is, but it doesn't make sense the similarly named functions do different things.

**Comment by LovelySanta** [comment]
So ingredients are always a list of different ingredients, even if there is only one ingredient.
For recipes, it does have 2 options

- `result` as the name, and `result_count` as the amount, `result_count` being optional, default to 1
- `results`, which is a table similar to the ingredients.

I do see that I forget to check the resultName in both cases... It should look like this:
```lua
    if data.raw["recipe"][recipeName].result then
      if data.raw["recipe"][recipeName].result == resultName then
        return data.raw["recipe"][recipeName].result_count or 1
      else
        return 0
      end
    elseif data.raw["recipe"][recipeName].results then
      for resultIndex, result in pairs(data.raw["recipe"][recipeName].results) do
        if (result.name or result[1] or "") == resultName then
          return data.raw["recipe"][recipeName].results[resultIndex].amount or 1
        end
      end
      return 0
```
I'll fix this for the next release.

**Comment by randomflyingtaco** [comment]
Alright, that makes sense, but then shouldn't the function name be getResultAmount instead of getResultCount (since you are giving the amount of a single result type instead of a count of the number of distinct result types)?
Also, will resultName be a required parameter?

**Comment by LovelySanta** [comment]
yeah maybe...

**Comment by LovelySanta** [comment]
I fixed this in the released version now. The resultName remains optional, if it is set to nil (or ommited), it will return the amount of the first item, otherwise it will return the amount of the specific item. The return value is nil when the prototype is invalid.

For now I decided to leave the function name as is. Renaming is always possible in the future.
